// Flat config: strict type-aware linting per DS-001. Workspaces extend this root config.
import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  {
    ignores: [
      "**/dist/**",
      "**/build/**",
      "**/node_modules/**",
      "pocs/**",
      ".claude/**",
      // @nyx/compact-wasm vendors the prebuilt wasm Compact compiler (compactc.js
      // glue + a reference copy of the PoC's Node driver). These are committed
      // binaries/verbatim vendored sources, not authored code — exclude the whole
      // vendor tree from repo-wide lint (it is regenerated by scripts/vendor.mjs).
      "packages/compact-wasm/vendor/**",
      // @nyx/nyxt-vault TS imports the Compact-generated contract in build/ (produced
      // by `compact compile`), so type-aware linting needs the toolchain. The whole
      // package is toolchain-gated (its typecheck/test guard on `compact` availability),
      // so exclude its build-dependent TS from the repo-wide lint too; it is linted
      // locally when the toolchain + generated build are present.
      "packages/nyxt-vault/src/index.ts",
      "packages/nyxt-vault/src/witnesses.ts",
      "packages/nyxt-vault/tests/**",
    ],
  },
  js.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  {
    languageOptions: {
      parserOptions: { projectService: true, tsconfigRootDir: import.meta.dirname },
    },
  },
  {
    // Plain-JS files that aren't part of any tsconfig — root config files (this
    // file, commitlint.config.mjs) and standalone Node scripts (scripts/*.mjs) —
    // can't be resolved by the type-aware project service. Lint them without type
    // information, and declare the Node globals they rely on so `no-undef` passes.
    files: ["**/*.config.mjs", "**/scripts/**/*.mjs"],
    ...tseslint.configs.disableTypeChecked,
    languageOptions: {
      ...tseslint.configs.disableTypeChecked.languageOptions,
      globals: { console: "readonly", process: "readonly" },
    },
  },
  prettier,
);
