/**
 * Signature-verification unit tests (T033).
 *
 * SECURITY-CRITICAL (constitution III): a hole here is an authentication bypass.
 * These prove the server's INTERNAL verification logic is self-consistent using a
 * synthetic BIP-340 Schnorr keypair generated by ledger-v8 itself — real execution,
 * no live wallet. They cover: valid signature → accept; tampered message → reject;
 * tampered signature → reject; key↔address mismatch → reject (the key-substitution
 * defence); and malformed inputs → reject without throwing (DoS-safe).
 *
 * ⚠️ OWNER-GATED GAP: whether Lace's real `signData` produces bytes identical to
 * {@link reconstructSignedBytes} is NOT proven here — it needs an empirical
 * round-trip against a live Lace browser (see verify.ts). These tests prove the
 * logic is INTERNALLY consistent, not that it matches a real wallet.
 */
import { describe, expect, it } from "vitest";
import {
  extractNonce,
  reconstructSignedBytes,
  verifyKeyAddressBinding,
  verifyMessageSignature,
} from "../../src/auth/verify.js";
import { makeIdentity, signMessage, siweMessage } from "./helpers.js";

describe("reconstructSignedBytes (T033)", () => {
  it("prepends the exact `midnight_signed_message:<byteLen>:` prefix over the UTF-8 payload", () => {
    const message = "hi";
    const bytes = reconstructSignedBytes(message);
    const expected = new TextEncoder().encode("midnight_signed_message:2:hi");
    expect(Buffer.from(bytes).equals(Buffer.from(expected))).toBe(true);
  });

  it("counts the byte length of the UTF-8 payload, not the character count", () => {
    // "é" is 2 UTF-8 bytes, so a 1-character message reconstructs with byteLen 2.
    const bytes = reconstructSignedBytes("é");
    const expected = new TextEncoder().encode("midnight_signed_message:2:é");
    expect(Buffer.from(bytes).equals(Buffer.from(expected))).toBe(true);
  });
});

describe("verifyMessageSignature (T033)", () => {
  it("accepts a signature produced over the reconstructed bytes (valid → accept)", () => {
    const id = makeIdentity();
    const message = siweMessage("nonce-abc");
    const signature = signMessage(id.signingKey, message);
    expect(verifyMessageSignature({ verifyingKey: id.verifyingKey, message, signature })).toBe(
      true,
    );
  });

  it("rejects when the message is tampered after signing (tampered message → reject)", () => {
    const id = makeIdentity();
    const message = siweMessage("nonce-abc");
    const signature = signMessage(id.signingKey, message);
    const tampered = siweMessage("nonce-abc") + " tampered";
    expect(
      verifyMessageSignature({ verifyingKey: id.verifyingKey, message: tampered, signature }),
    ).toBe(false);
  });

  it("rejects when the signature bytes are tampered (tampered signature → reject)", () => {
    const id = makeIdentity();
    const message = siweMessage("nonce-abc");
    const signature = signMessage(id.signingKey, message);
    // Flip the first hex nibble to a different valid hex digit → wrong signature.
    const first = signature[0] ?? "0";
    const flipped = (first === "a" ? "b" : "a") + signature.slice(1);
    expect(
      verifyMessageSignature({ verifyingKey: id.verifyingKey, message, signature: flipped }),
    ).toBe(false);
  });

  it("rejects a signature made by a different key (wrong key → reject)", () => {
    const signer = makeIdentity();
    const other = makeIdentity();
    const message = siweMessage("nonce-abc");
    const signature = signMessage(signer.signingKey, message);
    expect(verifyMessageSignature({ verifyingKey: other.verifyingKey, message, signature })).toBe(
      false,
    );
  });

  it("returns false (never throws) for malformed verifying-key / signature hex", () => {
    const message = siweMessage("nonce-abc");
    expect(
      verifyMessageSignature({ verifyingKey: "not-hex", message, signature: "also-not-hex" }),
    ).toBe(false);
    expect(verifyMessageSignature({ verifyingKey: "", message, signature: "" })).toBe(false);
  });
});

describe("verifyKeyAddressBinding (T033) — key-substitution defence", () => {
  it("accepts when the address is SHA-256(verifyingKey) (matching binding → accept)", () => {
    const id = makeIdentity();
    expect(verifyKeyAddressBinding({ verifyingKey: id.verifyingKey, address: id.address })).toBe(
      true,
    );
  });

  it("rejects a verifying key that does not hash to the submitted address (mismatch → reject)", () => {
    const signer = makeIdentity();
    const victim = makeIdentity();
    // Attacker submits the victim's address but their own key → must be rejected.
    expect(
      verifyKeyAddressBinding({ verifyingKey: signer.verifyingKey, address: victim.address }),
    ).toBe(false);
  });

  it("returns false (never throws) for a malformed or non-address Bech32m string", () => {
    const id = makeIdentity();
    expect(verifyKeyAddressBinding({ verifyingKey: id.verifyingKey, address: "not-bech32" })).toBe(
      false,
    );
    expect(verifyKeyAddressBinding({ verifyingKey: id.verifyingKey, address: "" })).toBe(false);
  });

  it("rejects when the verifying key itself is malformed", () => {
    const id = makeIdentity();
    expect(verifyKeyAddressBinding({ verifyingKey: "zzzz", address: id.address })).toBe(false);
  });
});

describe("extractNonce (T033)", () => {
  it("reads the nonce from the SIWE `Nonce:` line", () => {
    expect(extractNonce(siweMessage("abc123"))).toBe("abc123");
  });

  it("returns undefined when the message carries no nonce line", () => {
    expect(extractNonce("just some text with no nonce field")).toBeUndefined();
  });
});
